name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json' # package.json의 버전이 바뀔 때 주로 동작하게 하거나, 지금은 커밋 시 바로 실행되게
  workflow_dispatch: # 수동 실행 기능

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist -- -p always

      - name: Make Release Public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $VERSION = (Get-Content package.json | ConvertFrom-Json).version
          gh release edit "v$VERSION" --draft=false --notes-file release-notes.md

